FROM node:22-alpine

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

# Mở cổng mặc định của Vite
EXPOSE 5173

# Chạy lệnh dev thay vì build
CMD ["npm", "run", "dev", "--", "--host"]